### ISSUE TITLE
Question about the scaling factor

### ISSUE THREAD

**Issue by AlbertoRemus** [aimagelab/mcmr#5]
Hello, this work looks really interesting!

I've got one question about the scaling factor: is this method capable of retrieving the correct scaling factor during inference? Is this possible thanks to the (correctly scaled?) "meanshape" estimation?

Thanks in advance

**Comment by stefanopini** [comment]
Hi @AlbertoRemus ,
Yes, during inference the method predicts a pose that is composed of a scaling factor, a translation and a rotation.
It is not related to the meanshape estimation, all the meanshapes have roughly the same size that is scaled according to the scale value predicted by the pose module.

**Comment by AlbertoRemus** [comment]
@stefanopini many thanks for your reply

I would like to ask a related question to understand better: the pose you predict exploits the [Weakly perspective projection](https://sites.ecse.rpi.edu/~qji/CV/perspective_geometry2.pdf) as far as I understood this is suitable when the relative distance between objects is much lower than their average distance to the camera.

If however this constraint was not respected could your model be used anyway? 

https://github.com/aimagelab/mcmr/blob/e0c6ff09d7670d57881029f3aa0a8978773a2d39/datasets/cub/dataset.py#L80-L97

Here for instance in the dataset you work with a constant z, if however I had a dataset with object orientation and translation (in 3 coordinates with non constant z) as well as the intrinsic matrix K (hence the full perspective model) I think I can translate it to the weakly-perspective one but not viceversa, thus leaving somehow an ambiguity either in the predicted depth, is this correct?

**Comment by stefanopini** [comment]
Hi @AlbertoRemus , apologies for the late reply.

If I remember correctly, you're right. The projection is weakly perspective because we apply the projection using the same distance/scale factor for the entire object. If you have pictures of objects which are very close to the camera, you may not be able to learn and predict those objects perfectly due to the perspective distortions. I think the model could still be able to learn meaningful shapes if the distortions are limited.

Regarding the code you linked, we use a constant "base" z value, but also a scale factor `scale` (that the model learns to predict) that is used to change the size of the object instead of predicting a variable distance from the camera.

Regarding your case in particular, if you have the object orientation and translation, I think you're still using a weak perspective projection, since your translation on the z is [fixed for each object](https://shengchen-liu.github.io/gitbook_computer_vision/camera_and_images/Weak%20Perspective.html) (i.e. you apply the same transformation to each of its points, even if the points are at slightly different z distances from the camera).
If you have different z values in the dataset, I think you can either predict them directly or fix a z value and compute a scale factor, based on the actual z and the fixed z (and the focal length).

I hope this helps, please let me know if you have any other questions or something is not clear 🙂

**Comment by AlbertoRemus** [comment]
@stefanopini, many thanks for your clear and detailed explanation!
I'm going to explore all the possibilities you presented to me.

Hence I'm going to close this issue and open others if needed
